imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
#    - { resource: memcached.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    form:
        resources:
            - 'PROCERGSLoginCidadaoCoreBundle:Form:fields.html.twig'
    globals:
        fos_csrf_provider: "@form.csrf_provider"
        notifications_helper: "@notifications.helper"
        facebook_app_id: "%facebook_app_id%"
        background_picture_author: %background_picture.author%
        background_picture_link: %background_picture.link%
        app_router: "@router"
        tre_search_link: "%tre_search_link%"
        postalcode_search_link: "%postalcode_search_link%"

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ "PROCERGSLoginCidadaoCoreBundle", "PROCERGSLoginCidadaoNotificationBundle" ]
    #java: /usr/bin/java
    assets:
      bootstrap_fonts_woff:
          inputs:
              - 'bundles/procergslogincidadaocore/bootstrap/3.3.1/fonts/glyphicons-halflings-regular.woff'
          output: fonts/glyphicons-halflings-regular.woff
      bootstrap_fonts_ttf:
          inputs:
              - 'bundles/procergslogincidadaocore/bootstrap/3.3.1/fonts/glyphicons-halflings-regular.ttf'
          output: fonts/glyphicons-halflings-regular.ttf
      bootstrap_fonts_svg:
          inputs:
              - 'bundles/procergslogincidadaocore/bootstrap/3.3.1/fonts/glyphicons-halflings-regular.svg'
          output: fonts/glyphicons-halflings-regular.svg
      bootstrap_fonts_eot:
          inputs:
              - 'bundles/procergslogincidadaocore/bootstrap/3.3.1/fonts/glyphicons-halflings-regular.eot'
          output: fonts/glyphicons-halflings-regular.eot
      lc_base_js:
        inputs:
          - '@PROCERGSLoginCidadaoCoreBundle/Resources/public/js/jquery/1.11.0/jquery.min.js'
          - '@PROCERGSLoginCidadaoCoreBundle/Resources/public/bootstrap/3.3.1/js/bootstrap.min.js'
          - '@PROCERGSLoginCidadaoCoreBundle/Resources/public/bootstrap-switch/3.0.2/js/bootstrap-switch.min.js'
          - '@PROCERGSLoginCidadaoCoreBundle/Resources/public/js/hinclude/0.9.5/hinclude.min.js'
          - '@PROCERGSLoginCidadaoCoreBundle/Resources/public/js/jquery.mask.min.js'
          - '@PROCERGSLoginCidadaoCoreBundle/Resources/public/js/jquery.placeholder.js'
          - '@PROCERGSLoginCidadaoCoreBundle/Resources/public/js/jquery.infinitescroll.js'
          - '@PROCERGSLoginCidadaoCoreBundle/Resources/public/js/jquery.infinitescroll.local.js'
          - '@PROCERGSLoginCidadaoCoreBundle/Resources/public/js/jquery.visible.min.js'
          - '@PROCERGSLoginCidadaoCoreBundle/Resources/public/js/general.js'
      lc_base_css:
        inputs:
          - 'bundles/procergslogincidadaocore/bootstrap/3.3.1/css/bootstrap.min.css'
          - 'bundles/procergslogincidadaocore/bootstrap/3.3.1/css/bootstrap-theme.min.css'
          - 'bundles/procergslogincidadaocore/bootstrap-switch/3.0.2/css/bootstrap3/bootstrap-switch.min.css'
          - 'bundles/procergslogincidadaocore/css/general.css'
          - 'bundles/procergslogincidadaocore/css/navbar.css'
          - 'bundles/procergslogincidadaocore/css/ac.widget.css'
          - 'bundles/procergslogincidadaocore/css/common.grid.css'
          - 'bundles/procergslogincidadaocore/css/custom.recaptcha.css'
          - 'bundles/procergslogincidadaocore/css/list.buttons.css'
          - 'bundles/procergslogincidadaocore/css/notification.css'
      lc_logged_css:
        inputs:
          - '@lc_base_css'
          - 'bundles/procergslogincidadaocore/css/logged/logged.css'
          - 'bundles/procergslogincidadaonotification/css/notifications.css'

    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: %kernel.root_dir%/Resources/node_modules/uglify-js/bin/uglifyjs
        uglifycss:
            bin: %kernel.root_dir%/Resources/node_modules/uglifycss/uglifycss
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        dql:
          string_functions:
            right: PROCERGS\LoginCidadao\CoreBundle\DQL\Right
            countif: PROCERGS\LoginCidadao\CoreBundle\DQL\CountIf
            lowerunaccent: PROCERGS\LoginCidadao\CoreBundle\DQL\LowerUnaccent

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
    sender_address: %mailer_sender_mail%
    #delivery_address: %mailer_sender_mail%

fos_oauth_server:
  db_driver: orm
  client_class:         PROCERGS\OAuthBundle\Entity\Client
  access_token_class:   PROCERGS\OAuthBundle\Entity\AccessToken
  refresh_token_class:  PROCERGS\OAuthBundle\Entity\RefreshToken
  auth_code_class:      PROCERGS\OAuthBundle\Entity\AuthCode
  service:
      user_provider: fos_user.user_manager
      client_manager: procergs_logincidadao.oauth.client_manager
      options:
          supported_scopes: %lc_supported_scopes%

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: %user.class%
    registration:
        confirmation:
            enabled: false
            template: PROCERGSLoginCidadaoCoreBundle:Person:registration/email.html.twig
            from_email:
              address: %mailer_sender_mail%
              sender_name: %mailer_sender_name%
        form:
            type: procergs_person_registration
            validation_groups:  [LoginCidadaoRegistration]
    profile:
        form:
            type: procergs_person_profile
    resetting:
        email:
            template: PROCERGSLoginCidadaoCoreBundle:Person:resetting/email.html.twig
            from_email:
                address:        %mailer_sender_mail%
                sender_name:    %mailer_sender_name%
        form:
            type:               procergs_person_resetting
    service:
        user_manager: procergs_logincidadao.user_manager
        mailer: fos_user.mailer.twig_swift
    change_password:
        form:
            type:               procergs_change_password

# Audit Trail
simple_things_entity_audit:
    global_ignore_columns:
        - updatedAt
        - lastLogin
    audited_entities:
        - PROCERGS\LoginCidadao\APIBundle\Entity\LogoutKey

        - PROCERGS\LoginCidadao\CoreBundle\Entity\Authorization
        - PROCERGS\LoginCidadao\CoreBundle\Entity\BackupCode
        - PROCERGS\LoginCidadao\CoreBundle\Entity\City
        - PROCERGS\LoginCidadao\CoreBundle\Entity\ClientSuggestion
        - PROCERGS\LoginCidadao\CoreBundle\Entity\Country
        - PROCERGS\LoginCidadao\CoreBundle\Entity\IdCard
        - PROCERGS\LoginCidadao\CoreBundle\Entity\Person
        - PROCERGS\LoginCidadao\CoreBundle\Entity\PersonAddress
        - PROCERGS\LoginCidadao\CoreBundle\Entity\SentEmail
        - PROCERGS\LoginCidadao\CoreBundle\Entity\State

        - PROCERGS\LoginCidadao\NotificationBundle\Entity\Broadcast
        - PROCERGS\LoginCidadao\NotificationBundle\Entity\Category
        - PROCERGS\LoginCidadao\NotificationBundle\Entity\Notification
        - PROCERGS\LoginCidadao\NotificationBundle\Entity\NotificationToken
        - PROCERGS\LoginCidadao\NotificationBundle\Entity\PersonNotificationOption
        - PROCERGS\LoginCidadao\NotificationBundle\Entity\Placeholder

        - PROCERGS\OAuthBundle\Entity\AccessToken
        - PROCERGS\OAuthBundle\Entity\AuthCode
        - PROCERGS\OAuthBundle\Entity\Client
        - PROCERGS\OAuthBundle\Entity\RefreshToken

fos_facebook:
    alias:  facebook
    app_id: %facebook_app_id%
    secret: %facebook_app_secret%
    cookie: true
    permissions: %facebook_app_scope%

hwi_oauth:
    connect:
        confirmation: false
        account_connector: procergs.hwi_twitter.user_provider
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            twitter: twitterId
            google: googleId
    resource_owners:
        twitter:
            type:           twitter
            client_id:      %twitter_app_key%
            client_secret:  %twitter_app_secret%
            scope:          "email"
        google:
            type:           google
            client_id:      %google_app_key%
            client_secret:  %google_app_secret%
            scope:          "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
    http_client:
        verify_peer: false

parameters:
    user.class: PROCERGS\LoginCidadao\CoreBundle\Entity\Person
    buzz.client.class: Donato\Generic\HWIOAuthProxyBundle\Buzz\Client\CurlProxy
    hwi_oauth.resource_owner.twitter.class: PROCERGS\LoginCidadao\CoreBundle\OAuth\ResourceOwner\TwitterResourceOwner
    lc_supported_scopes: 'id username first_name last_name full_name name cpf birthdate email city picture public_profile badges country state city addresses id_cards get_all_notifications notifications cep mobile logout'
    lc_idcard_country_acronym: BR

ewz_recaptcha:
    public_key:   %recaptcha_public_key%
    private_key:  %recaptcha_private_key%
    secure:       true
    locale_key:   kernel.default_locale
    http_proxy: %http_proxy%

# Uploader
knp_gaufrette:
    stream_wrapper: ~

    adapters:
        user_local_adapter:
            local:
                directory: %kernel.root_dir%/../web/uploads/profile-pictures
#        user_ftp_adapter:
#            ftp:
#                host: corona.procergs.com.br
#                username: %user_profile_ftp_username%
#                password: %user_profile_ftp_password%
#                directory: %user_profile_ftp_directory%
#                create: false
#                mode: FTP_BINARY
#        user_cache_adapter:
#            cache:
#                source: user_ftp_adapter
#                cache: user_local_adapter
#                ttl: 1800

    filesystems:
        user_image_fs:
            adapter:    user_local_adapter

vich_uploader:
    db_driver:  orm
    twig:       true
    storage:    gaufrette
    mappings:
        user_image:
            uri_prefix:         %uri_root%/uploads/profile-pictures
            upload_destination: user_image_fs
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false

# Disabling annotations is needed by FOS Rest Bundle
sensio_framework_extra:
    view: { annotations: false }
    router: { annotations: true }
    request: { converters: true }

fos_rest:
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        force_redirects:
            html: true
        formats:
            json: true
            xml: true
        templating_formats:
            html: true
#    format_listener:
#        rules:
#            - { path: ^/api/v1, priorities: [ html, json, xml ], fallback_format: json, prefer_extension: true }
#            - { path: '^/', stop: true }
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true
    disable_csrf_role: ROLE_API

nelmio_api_doc:
    name: MeuRS API

jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/serializer/FOSUB"

scheb_two_factor:
    trusted_computer:
        enabled: false
        cookie_name: lc_trusted_computer
        cookie_lifetime: 2592000

    exclude_pattern: ^/(css|js|images|api)

    parameter_names:
        auth_code: _auth_code
        trusted: _trusted

    email:
        enabled: false
        mailer: swiftmailer
        sender_email: %mailer_sender_mail%
        digits: 6
        template: PROCERGSLoginCidadaoCoreBundle:TwoFactorAuthentication:form.html.twig

    google:
        enabled: true
        server_name: %site_domain%
        template: PROCERGSLoginCidadaoCoreBundle:TwoFactorAuthentication:form.html.twig

    persister: ~
    model_manager_name: ~

    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - FOS\FacebookBundle\Security\Authentication\Token\FacebookUserToken
