imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: memcached.yml }
    - { resource: "@LoginCidadaoTOSBundle/Resources/config/config.yml" }

framework:
    #esi:             ~
    assets:
        version: '2016-03-29'
        version_format: '%%s?version=%%s'
        base_path: ~
    translator:
        enabled: true
        fallback: %locale%
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: %trusted_proxies%
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    form_themes:
        - 'LoginCidadaoCoreBundle:Form:fields.html.twig'
    globals:
        fos_csrf_provider: "@security.csrf.token_manager"
        notifications_helper: "@notifications.helper"
        facebook_app_id: "%facebook_app_id%"
        app_router: "@router"
        postalcode_search_link: 
        third_party_login: %third_party_login%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #java: /usr/bin/java
    assets:
      bootstrap_fonts_woff:
          inputs:
              - 'assets/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.woff'
          output: fonts/glyphicons-halflings-regular.woff
      bootstrap_fonts_ttf:
          inputs:
              - 'assets/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf'
          output: fonts/glyphicons-halflings-regular.ttf
      bootstrap_fonts_svg:
          inputs:
              - 'assets/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.svg'
          output: fonts/glyphicons-halflings-regular.svg
      bootstrap_fonts_eot:
          inputs:
              - 'assets/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.eot'
          output: fonts/glyphicons-halflings-regular.eot
      lc_base_js:
        inputs:
          - '@LoginCidadaoCoreBundle/Resources/public/js/jquery/1.11.0/jquery.min.js'
          - '@LoginCidadaoCoreBundle/Resources/public/bootstrap/3.3.1/js/bootstrap.min.js'
          - '@LoginCidadaoCoreBundle/Resources/public/bootstrap-switch/3.0.2/js/bootstrap-switch.min.js'
          - '@LoginCidadaoCoreBundle/Resources/public/js/hinclude/0.9.5/hinclude.min.js'
          - '@LoginCidadaoCoreBundle/Resources/public/js/jquery.mask.min.js'
          - '@LoginCidadaoCoreBundle/Resources/public/js/jquery.placeholder.js'
          - '@LoginCidadaoCoreBundle/Resources/public/js/jquery.infinitescroll.js'
          - '@LoginCidadaoCoreBundle/Resources/public/js/jquery.infinitescroll.local.js'
          - '@LoginCidadaoCoreBundle/Resources/public/js/jquery.visible.min.js'
          - '@LoginCidadaoCoreBundle/Resources/public/js/jquery.preventDoubleSubmission.js'
          - '@LoginCidadaoCoreBundle/Resources/public/js/general.js'
      bootstrap_css:
        inputs:
          - 'assets/vendor/bootstrap/dist/css/bootstrap.min.css'
          - '@LoginCidadaoCoreBundle/Resources/public/bootstrap/3.3.1/css/bootstrap-theme.min.css'
          - '@LoginCidadaoCoreBundle/Resources/public/bootstrap-switch/3.0.2/css/bootstrap3/bootstrap-switch.min.css'
      lc_login_register_css:
        inputs:
          - 'bundles/logincidadaocore/css/login_register/*.css'
      lc_base_css:
        inputs:
          - '@bootstrap_css'
          - 'bundles/logincidadaocore/css/general.css'
          - 'bundles/logincidadaocore/css/navbar.css'
          - 'bundles/logincidadaocore/css/ac.widget.css'
          - 'bundles/logincidadaocore/css/common.grid.css'
          - 'bundles/logincidadaocore/css/list.buttons.css'
          - 'bundles/logincidadaocore/css/notification.css'
      lc_logged_css:
        inputs:
          - '@lc_base_css'
          - 'bundles/logincidadaocore/css/logged/logged.css'
          - 'bundles/logincidadaonotification/css/notifications.css'

    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: %kernel.root_dir%/Resources/node_modules/uglify-js/bin/uglifyjs
        uglifycss:
            bin: %kernel.root_dir%/Resources/node_modules/uglifycss/uglifycss
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        resolve_target_entities:
            LoginCidadao\CoreBundle\Model\PersonInterface: %user.class%
            LoginCidadao\OAuthBundle\Model\OrganizationInterface: %organization.class%
            LoginCidadao\OAuthBundle\Model\ClientInterface: %oauth_client.class%
        dql:
          string_functions:
            right: LoginCidadao\CoreBundle\DQL\Right
            countif: LoginCidadao\CoreBundle\DQL\CountIf
            lowerunaccent: LoginCidadao\CoreBundle\DQL\LowerUnaccent

          datetime_functions:
                date:       Oro\ORM\Query\AST\Functions\SimpleFunction

          numeric_functions:
              dayofweek:    Oro\ORM\Query\AST\Functions\SimpleFunction
# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
    sender_address: %mailer_sender_mail%
    #delivery_address: %mailer_sender_mail%

fos_oauth_server:
  db_driver: orm
  client_class:         LoginCidadao\OAuthBundle\Entity\Client
  access_token_class:   LoginCidadao\OAuthBundle\Entity\AccessToken
  refresh_token_class:  LoginCidadao\OAuthBundle\Entity\RefreshToken
  auth_code_class:      LoginCidadao\OAuthBundle\Entity\AuthCode
  service:
      user_provider: fos_user.user_manager
      client_manager: lc.oauth.client_manager
      options:
          supported_scopes: %lc_supported_scopes%

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: %user.class%
    registration:
        confirmation:
            enabled: false
            template: LoginCidadaoCoreBundle:Person:registration/email.html.twig
            from_email:
              address: %mailer_sender_mail%
              sender_name: %mailer_sender_name%
        form:
            type: LoginCidadao\CoreBundle\Form\Type\RegistrationFormType
            validation_groups:  [LoginCidadaoRegistration]
    profile:
        form:
            type: LoginCidadao\CoreBundle\Form\Type\ProfileFormType
    resetting:
        email:
            template: LoginCidadaoCoreBundle:Person:resetting/email.html.twig
            from_email:
                address:        %mailer_sender_mail%
                sender_name:    %mailer_sender_name%
        form:
            type:               lc_person_resetting
    service:
        user_manager: lc.user_manager
        mailer: fos_user.mailer.twig_swift
    change_password:
        form:
            type: LoginCidadao\CoreBundle\Form\Type\ChangePasswordFormType

# Audit Trail
simple_things_entity_audit:
    global_ignore_columns:
        - updatedAt
        - lastLogin
    audited_entities:
        - LoginCidadao\APIBundle\Entity\LogoutKey

        - LoginCidadao\CoreBundle\Entity\Authorization
        - LoginCidadao\CoreBundle\Entity\BackupCode
        - LoginCidadao\CoreBundle\Entity\City
        - LoginCidadao\CoreBundle\Entity\ClientSuggestion
        - LoginCidadao\CoreBundle\Entity\Country
        - LoginCidadao\CoreBundle\Entity\IdCard
        - LoginCidadao\CoreBundle\Entity\ImpersonationReport
        - LoginCidadao\CoreBundle\Entity\Person
        - LoginCidadao\CoreBundle\Entity\PersonAddress
        - LoginCidadao\CoreBundle\Entity\SentEmail
        - LoginCidadao\CoreBundle\Entity\State

        - LoginCidadao\NotificationBundle\Entity\Broadcast
        - LoginCidadao\NotificationBundle\Entity\Category
        - LoginCidadao\NotificationBundle\Entity\Notification
        - LoginCidadao\NotificationBundle\Entity\NotificationToken
        - LoginCidadao\NotificationBundle\Entity\PersonNotificationOption
        - LoginCidadao\NotificationBundle\Entity\Placeholder

        - LoginCidadao\OAuthBundle\Entity\AccessToken
        - LoginCidadao\OAuthBundle\Entity\AuthCode
        - LoginCidadao\OAuthBundle\Entity\Client
        - LoginCidadao\OAuthBundle\Entity\RefreshToken
        - LoginCidadao\OAuthBundle\Entity\Organization

fos_facebook:
    alias:  facebook
    app_id: %facebook_app_id%
    secret: %facebook_app_secret%
    cookie: true
    permissions: %facebook_app_scope%

hwi_oauth:
    connect:
        confirmation: false
        account_connector: lc.hwi_twitter.user_provider
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            twitter: twitterId
            google: googleId
    resource_owners:
        twitter:
            type:           twitter
            client_id:      %twitter_app_key%
            client_secret:  %twitter_app_secret%
            scope:          "email"
        google:
            type:           google
            client_id:      %google_app_key%
            client_secret:  %google_app_secret%
            scope:          "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
    http_client:
        verify_peer: false

parameters:
    user.class: LoginCidadao\CoreBundle\Entity\Person
    buzz.client.class: Donato\Generic\HWIOAuthProxyBundle\Buzz\Client\CurlProxy
    hwi_oauth.resource_owner.twitter.class: LoginCidadao\CoreBundle\OAuth\ResourceOwner\TwitterResourceOwner
    lc_public_scopes_oidc: 'openid sub name given_name family_name full_name preferred_username picture email email_verified birthdate phone_number address updated_at'
    lc_public_scopes_oauth2: 'public_profile username first_name last_name full_name cpf city public_profile country state addresses id_cards mobile logout'
    lc_public_scopes: %lc_public_scopes_oidc% %lc_public_scopes_oauth2%
    lc_reserved_scopes: 'get_all_notifications notifications voter_registration'
    lc_supported_scopes: %lc_public_scopes% %lc_reserved_scopes%
    lc_idcard_country_acronym: BR

    oauth2.user_provider.class: LoginCidadao\CoreBundle\Security\OIDC\UserProvider
    organization.class: LoginCidadao\OAuthBundle\Entity\Organization
    oauth_client.class: LoginCidadao\OAuthBundle\Entity\Client

beelab_recaptcha2:
    site_key: "%recaptcha_public_key%"
    secret: "%recaptcha_private_key%"

# Uploader
knp_gaufrette:
    stream_wrapper: ~

    adapters:
        user_local_adapter:
            local:
                directory: %user_profile_upload_dir%
        client_local_adapter:
            local:
                directory: %client_image_upload_dir%
        jwks_local_adapter:
            local:
                directory: %jwks_dir%

    filesystems:
        user_image_fs:
            adapter:    user_local_adapter
        client_image_fs:
            adapter:    client_local_adapter
        jwks_fs:
            adapter:    jwks_local_adapter

vich_uploader:
    db_driver:  orm
    twig:       true
    storage:    gaufrette
    mappings:
        user_image:
            uri_prefix:         %uri_root%/uploads/profile-pictures
            upload_destination: user_image_fs
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
        client_image:
            uri_prefix:         %uri_root%/uploads/client-pictures
            upload_destination: client_image_fs
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false

# Disabling annotations is needed by FOS Rest Bundle
sensio_framework_extra:
    view: { annotations: false }
    router: { annotations: true }
    request: { converters: true }

fos_rest:
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        force_redirects:
            html: true
        formats:
            json: true
            xml: true
        templating_formats:
            html: true
#    format_listener:
#        rules:
#            - { path: ^/api/v1, priorities: [ html, json, xml ], fallback_format: json, prefer_extension: true }
#            - { path: '^/', stop: true }
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true
    disable_csrf_role: ROLE_API

nelmio_api_doc:
    name: MeuRS API

jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/serializer/FOSUB"

scheb_two_factor:
    trusted_computer:
        enabled: false
        cookie_name: lc_trusted_computer
        cookie_lifetime: 2592000

    exclude_pattern: ^/(css|js|images|api)

    parameter_names:
        auth_code: _auth_code
        trusted: _trusted

    email:
        enabled: false
        mailer: swiftmailer
        sender_email: %mailer_sender_mail%
        digits: 6
        template: LoginCidadaoCoreBundle:TwoFactorAuthentication:form.html.twig

    google:
        enabled: true
        server_name: %site_domain%
        issuer: %two_factor_issuer%
        template: LoginCidadaoCoreBundle:TwoFactorAuthentication:form.html.twig

    persister: ~
    model_manager_name: ~

    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - HWI\Bundle\OAuthBundle\Security\Core\Authentication\Token\OAuthToken
        - FOS\FacebookBundle\Security\Authentication\Token\FacebookUserToken

nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']

nelmio_security:
    # signs/verifies all cookies
    signed_cookie:
        names: [ ]
    encrypted_cookie:
        names: [ ]
    # prevents framing of the entire site
    clickjacking:
        paths:
            '^/.*': DENY
    # prevents redirections outside the website's domain
    external_redirects:
        abort: false
        log: true

    # prevents inline scripts, unsafe eval, external scripts/images/styles/frames, etc
    csp:
        report_logger_service: monolog.logger.security
        report:
            report-uri: [/nelmio/csp/report]
            default-src: [ 'self' ]
            # There's no flash on our site
            object-src:
                - 'none'
            script-src:
                - 'https://connect.facebook.net/'
                - 'http://connect.facebook.net/'
                - 'http://www.google-analytics.com/'
                - 'https://www.google-analytics.com/'
                - 'http://browser-update.org/'
                - 'https://www.google.com/'
                - 'https://www.gstatic.com/recaptcha/'
                - 'unsafe-inline'
                - 'unsafe-eval'
                - 'self'
            style-src:
                - 'https://www.google.com/'
                - 'https://ajax.googleapis.com/'
                - 'unsafe-inline'
                - 'self'
            font-src:
                - 'https://themes.googleusercontent.com/'
                - 'self'
            img-src:
                - '*'
            frame-src:
                - 'https://s-static.ak.facebook.com'
                - 'http://static.ak.facebook.com'
                - 'https://www.facebook.com'
        enforce:
            # see https://github.com/nelmio/NelmioSecurityBundle/issues/32
            report-uri: [/nelmio/csp/report]
            script-src:
                - 'https://connect.facebook.net/'
                - 'http://connect.facebook.net/'
                - 'http://www.google-analytics.com/'
                - 'https://www.google-analytics.com/'
                - 'http://browser-update.org/'
                - 'https://www.google.com/'
                - 'https://www.gstatic.com/recaptcha/'
                - 'https://ajax.googleapis.com/'
                - 'unsafe-inline'
                - 'unsafe-eval'
                - 'self'

    # disables content type sniffing for script resources
    content_type:
        nosniff: true

    # Forces Microsoft's XSS-Protection with
    # its block mode
    xss_protection:
        enabled: false
        mode_block: false

liip_monitor:
    enable_controller: true
    checks:
        memcache:
            main:
                host: %memcached_host%
                port: %memcached_port%

        doctrine_dbal: default

        readable_directory:
            - '%kernel.cache_dir%'
            - '%user_profile_upload_dir%'
            - '%client_image_upload_dir%'

        writable_directory:
            - '%kernel.cache_dir%'
            - '%user_profile_upload_dir%'
            - '%client_image_upload_dir%'

services:
    fos_user.doctrine_registry:
        alias: doctrine

donato_path_well:
    enabled: '%check_pathwell_topologies%'
