# Monitor
_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.xml"
    prefix: /monitor/health

#Nelmio Security
nelmio_security:
    path:     /nelmio/csp/report
    defaults: { _controller: nelmio_security.csp_reporter_controller:indexAction }
    methods:  [POST]

# OpenID Connect
oauth2_server:
    resource: "@OAuth2ServerBundle/Controller/"
    type:     annotation
    prefix:   /openid/connect/

lc_oidc_dr:
    type:     rest
    resource: LoginCidadao\OpenIDBundle\Controller\ClientRegistrationController

lc_oidc_discovery:
    type:     rest
    resource: LoginCidadao\OpenIDBundle\Controller\WellKnownController

lc_oidc:
    resource: "@LoginCidadaoOpenIDBundle/Controller/"
    type:     annotation
    prefix:   /

fos_oauth_server_authorize:
    path: /oauth/v2/auth
    methods:  [GET]
    defaults:  { _controller: LoginCidadaoOpenIDBundle:Authorize:validateAuthorize }

fos_oauth_server_authorize_post:
    path: /oauth/v2/auth
    methods:  [POST]
    defaults:  { _controller: LoginCidadaoOpenIDBundle:Authorize:handleAuthorize }

# Terms of Service
tos:
    resource: "@LoginCidadaoTOSBundle/Controller/"
    type:     annotation
    prefix:   /

#HWI OAuth
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

facebook_login:
    path: /login/check-facebook

twitter_login:
    path: /login/check-twitter

google_login:
    path: /login/check-google

#API
lc_api:
    type: rest
    resource: "@LoginCidadaoAPIBundle/Resources/config/routing.yml"
    prefix:   /api/v1

# API Doc
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

# login-cidadao
lc_locale:
    resource: "@LoginCidadaoLocaleBundle/Controller/"
    type:     annotation
    prefix:   /locale

lc_core:
    resource: "@LoginCidadaoCoreBundle/Resources/config/routing.yml"
    prefix:   /
lc_home:
    defaults: { _controller: FOSUserBundle:Security:login }
    path:   /

# Audit
simple_things_entity_audit:
    resource: "@SimpleThingsEntityAuditBundle/Resources/config/routing.yml"
    prefix: /audit

# OAuth Routes
lc_oauth:
    resource: "@LoginCidadaoOAuthBundle/Resources/config/routing.yml"
    prefix:   /

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

# UserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# Static Pages
lc_about:
    path: /about
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'LoginCidadaoCoreBundle:Info:about.html.twig'

lc_privacy:
    path: /privacy
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'LoginCidadaoCoreBundle:Info:privacy.html.twig'

lc_duplicate_email:
    path: /register/duplicate-email
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'LoginCidadaoCoreBundle:Info:duplicate_email.html.twig'
