security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha512
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:
            - FEATURE_PROD
        ROLE_DEV:
            - ROLE_USER
            - ROLE_ORGANIZATIONS_BIND_CLIENT
        ROLE_SUPER:
            - ROLE_DEV
            - ROLE_ORGANIZATIONS_CREATE
            - ROLE_ORGANIZATIONS_EDIT
            - ROLE_ORGANIZATIONS_VALIDATE
            - ROLE_ORGANIZATIONS_LIST_ALL
        ROLE_ADMIN:
            - ROLE_SUPER
            - ROLE_EDIT_CLIENT_ALLOWED_SCOPES
            - ROLE_ORGANIZATIONS_DELETE
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
            - FEATURE_ALPHA
            - ROLE_ORGANIZATIONS_EDIT_ANY_ORG
            - ROLE_ORGANIZATIONS_MANAGE_MEMBERS_ANY_ORG
            - ROLE_ORGANIZATIONS_BIND_CLIENT_ANY_ORG
            - ROLE_ORGANIZATIONS_CAN_TRUST
            - ROLE_ORGANIZATIONS_DELETE_ANY_ORG

        FEATURE_ALPHA:      FEATURE_BETA, FEATURE_ORGANIZATIONS
        FEATURE_BETA:       FEATURE_PROD
        FEATURE_PROD:       FEATURE_2FACTOR_AUTH
        FEATURE_IGP_VALIDATION:
        FEATURE_ORGANIZATIONS:

    providers:
        chainprovider:
            chain:
                providers: [fos_userbundle, fos_facebook_provider]
        fos_userbundle:
            id: lc.user_provider
        fos_facebook_provider:
            id: fos_facebook.user.login
        oauth2:
            id: oauth2.user_provider

    firewalls:
        oauth_token:
            pattern:  ^/(oauth/v2/)?token
            security: false

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main2:
            pattern: ^/facebook
            context: context_key
            fos_facebook:
                app_url: ""
                server_url: %facebook_app_this_url%
                login_path: /login
                check_path: /facebook/login_check
                default_target_path: fos_user_profile_edit
                success_handler: security.authentication.success_handler
                provider: fos_facebook_provider

        main:
            context: context_key
            pattern: ^/(?!api|!oauth)
            switch_user: true

            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~

            fos_facebook:
                app_url: ""
                server_url: %facebook_app_this_url%
                login_path: /login
                check_path: /facebook/login_check
                default_target_path: fos_user_profile_edit
                success_handler: security.authentication.success_handler
                provider: fos_facebook_provider

            oauth:
                resource_owners:
                    twitter:    "/login/check-twitter"
                    google:    "/login/check-google"
                login_path:   /login
                use_forward:  false
                failure_path: /login
                default_target_path: fos_user_profile_edit
                success_handler: security.authentication.success_handler
                oauth_user_provider:
                    service:  lc.hwi_twitter.user_provider

            form_login:
                provider:       fos_userbundle
                csrf_provider:  security.csrf.token_manager
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                username_parameter: login_form_type[username]
                password_parameter: login_form_type[password]
                csrf_parameter: login_form_type[csrf_token]
                always_use_default_target_path: false
                default_target_path:            fos_user_profile_edit
                target_path_parameter:          _target_path
                use_referer:                    true

            logout:
                path: /logout
            anonymous:  true

        oauth_authorize:
            pattern:  ^/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login
                always_use_default_target_path: false
                default_target_path:            fos_user_profile_edit
                target_path_parameter:          _target_path
                use_referer:                    true
            anonymous: false


        api:
          pattern:    ^/api/v1(?!/public)
          fos_oauth:  true
          stateless:  true
          anonymous:  true

    access_control:
        - { path: ^/admin, role: [ROLE_SUPER] }
        - { path: ^/dev, role: [ROLE_DEV] }

        - { path: ^/api/v1/address/(cities|states|countries)/search, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/address/cities/prefetch, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/public/lc_consultaCep2, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }

        - { path: ^/oauth$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.well-known, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/openid/connect/authorize, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/openid/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/connect/twitter$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/google$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/facebook$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/monitor/health, role: IS_AUTHENTICATED_ANONYMOUSLY, ip: %allowed_monitors% }

        - { path: ^/contact$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/general$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/privacy$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/about$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/help$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/person/checkEmailAvailable, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/job, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/external/navbar.js, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/logout/if-not-remembered, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/terms$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/profile/edit, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/profile/change-username, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/profile/change-password, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/person, role: IS_AUTHENTICATED_REMEMBERED }
