parameters:
    security.authentication.success_handler.class: PROCERGS\LoginCidadao\CoreBundle\Handler\AuthenticationSuccessHandler
    fos_facebook.user.login.class: PROCERGS\LoginCidadao\CoreBundle\Security\User\Provider\FacebookProvider
    procergs.hwi_twitter.user_provider.class: PROCERGS\LoginCidadao\CoreBundle\Security\User\Provider\FOSUBUserProvider
    procergs_person.registration.form.type.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\RegistrationFormType
    procergs_person.profile.form.type.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\ProfileFormType
    procergs_person.revoke_authorization.form.type.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\RevokeAuthorizationFormType
    procergs_person.resetting.form.type.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\ResettingFormType
    procergs_logincidadao.change.password.form.type.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\ChangePasswordFormType
    procergs_logincidadao.person.address.form.type.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\PersonAddressFormType
    procergs_logincidadao.city.selector.form.type.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\CitySelectorType
    procergs_logincidadao.state.selector.form.type.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\StateSelectorType
    procergs_logincidadao.country.selector.form.type.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\CountrySelectorType
    procergs_logincidadao.user_provider.class: PROCERGS\LoginCidadao\CoreBundle\Security\User\Provider\LoginCidadaoProvider
    procergs_logincidadao.user_manager.class: PROCERGS\LoginCidadao\CoreBundle\Security\User\Manager\UserManager
    procergs_logincidadao.user_register.class: PROCERGS\LoginCidadao\CoreBundle\EventListener\RegisterListner
    procergs_logincidadao.profile_edit.class: PROCERGS\LoginCidadao\CoreBundle\EventListener\ProfileEditListner
    procergs_logincidadao.change.password.listener.class: PROCERGS\LoginCidadao\CoreBundle\EventListener\ChangePasswordListener
    procergs_logincidadao.resetting.listener.class: PROCERGS\LoginCidadao\CoreBundle\EventListener\ResettingListener
    procergs_logincidadao.mailer.class: PROCERGS\LoginCidadao\CoreBundle\Mailer\TwigSwiftMailer
    kernel.listener.logged_in_user_listener.class: PROCERGS\LoginCidadao\CoreBundle\EventListener\LoggedInUserListener
    kernel.listener.exceptions_listener.class: PROCERGS\LoginCidadao\CoreBundle\EventListener\ExceptionListener
    procergs_login_cidadao_notification.subscriber.class: PROCERGS\LoginCidadao\CoreBundle\EventListener\NotificationsSubscriber

    procergs_logincidadao_core.emailChanged.template: PROCERGSLoginCidadaoCoreBundle:Person:emailChangedMessage.html.twig
    procergs_logincidadao_core.notification.email.template: PROCERGSLoginCidadaoCoreBundle:Email:notification.html.twig

    procergs_logincidadao.postalcode.search.form.type.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\SearchPostalCodeFormType

    procergs.person.serialize.listenner.class: PROCERGS\LoginCidadao\CoreBundle\EventListener\PersonSerializeEventListenner

    procergs_logincidadao.idcard.form.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\IdCardType
    procergs_logincidadao.security.helper.class: PROCERGS\LoginCidadao\CoreBundle\Helper\SecurityHelper
    account.security_listener.class: PROCERGS\LoginCidadao\CoreBundle\EventListener\SecurityListener

services:
    procergs_lc.command.populate_database:
        class: PROCERGS\LoginCidadao\CoreBundle\Command\PopulateDatabaseCommand
        tags:
            - { name: console.command }

    security.authentication.success_handler:
        class: %security.authentication.success_handler.class%
        public: false
        arguments: ["@router", [], "@doctrine.orm.entity_manager", "@session", "@security.http_utils", "@notifications.helper"]
        calls:
            - [setContainer, ["@service_container"]]

    fos_facebook.user.login:
        class: %fos_facebook.user.login.class%
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"
            dispatcher: "@event_dispatcher"
            formFactory: "@fos_user.registration.form.factory"

    procergs.hwi_twitter.user_provider:
        class: %procergs.hwi_twitter.user_provider.class%
        arguments: [ "@fos_user.user_manager", "@session", "@event_dispatcher", "@service_container", "@fos_user.registration.form.factory", { twitter: twitterId, google: googleId }, %http_proxy% ]

    procergs_person.registration.form.type:
        class: %procergs_person.registration.form.type.class%
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: procergs_person_registration }

    procergs_person.profile.form.type:
        class: %procergs_person.profile.form.type.class%
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: procergs_person_profile }
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
            - [ setDefaultCountryIso2, [%default_country_iso2%] ]

    procergs_person.revoke_authorization.form.type:
        class: %procergs_person.revoke_authorization.form.type.class%
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: procergs_revoke_authorization }

    procergs_person.resetting.form.type:
        class: %procergs_person.resetting.form.type.class%
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: procergs_person_resetting }

    procergs_logincidadao.postalcode.search.form.type:
        class: %procergs_logincidadao.postalcode.search.form.type.class%
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: search_postalcode_form_type }
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]

    procergs_logincidadao.user_provider:
        class: %procergs_logincidadao.user_provider.class%
        arguments: ["@fos_user.user_manager"]

    procergs_logincidadao.user_manager:
        class: %procergs_logincidadao.user_manager.class%
        arguments: ["@security.encoder_factory", "@fos_user.util.username_canonicalizer", "@fos_user.util.email_canonicalizer", "@fos_user.entity_manager", %user.class%, "@service_container"]

    procergs_logincidadao.login.form.type:
        class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\LoginFormType
        tags:
            - { name: form.type, alias: login_form_type }
        calls:
            - [setContainer, ["@service_container"]]

    procergs_logincidadao.login.twig.extension:
        class: PROCERGS\LoginCidadao\CoreBundle\Twig\Extension\LoginCidadaoExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension, alias: login_twig_extension }

    procergs_logincidadao.security.authentication.listener:
        class: PROCERGS\LoginCidadao\CoreBundle\Security\Http\Firewall\LoginCidadaoListener
        parent: security.authentication.listener.form
        abstract: true
        calls:
            - [setContainer, ["@service_container"]]

    procergs_logincidadao.user_register:
        class: %procergs_logincidadao.user_register.class%
        arguments: ["@router", "@session", "@translator", "@fos_user.mailer", "@fos_user.util.token_generator", "@notifications.helper", "%registration.email.unconfirmed_time%", "%lc_supported_scopes%", "@procergs.notification.handler" ]
        tags:
            - { name: kernel.event_subscriber }
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]

    procergs_logincidadao.profile_edit:
        class: %procergs_logincidadao.profile_edit.class%
        arguments: ["@procergs_logincidadao.mailer", "@fos_user.mailer", "@fos_user.util.token_generator", "@router", "@session", "@security.context", "@notifications.helper", "%registration.email.unconfirmed_time%"]
        tags:
            - { name: kernel.event_subscriber }
        calls:
            - [setCpfEmptyTime, ["%registration.cpf.empty_time%"]]
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
            - [setUserManager, ["@fos_user.user_manager"]]

    procergs_logincidadao.change.password.form.type:
        class: %procergs_logincidadao.change.password.form.type.class%
        arguments: [%fos_user.model.user.class%, "@security.context"]
        tags:
            - { name: form.type, alias: procergs_change_password }

    procergs_logincidadao.change_password_listener:
        class: %procergs_logincidadao.change.password.listener.class%
        arguments: ["@router", "@notifications.helper"]
        tags:
            - { name: kernel.event_subscriber }

    procergs_logincidadao.resetting_listener:
        class: %procergs_logincidadao.resetting.listener.class%
        arguments: ["@router", %fos_user.resetting.token_ttl%]
        tags:
            - { name: kernel.event_subscriber }

    procergs_logincidadao.mailer:
        class: %procergs_logincidadao.mailer.class%
        arguments: [ "@mailer", "@router", "@twig", { "template": { "confirmation": %fos_user.registration.confirmation.template%, "resetting": %fos_user.resetting.email.template%, "email_changed": %procergs_logincidadao_core.emailChanged.template%, "notification_email": %procergs_logincidadao_core.notification.email.template% }, "from_email": { "confirmation": %fos_user.registration.confirmation.from_email%, "resetting": %fos_user.resetting.email.from_email%, "email_changed": %mailer_sender_mail%, "email_sender_name": %mailer_sender_name% } } ]

    kernel.listener.logged_in_user_listener:
        class: %kernel.listener.logged_in_user_listener.class%
        arguments: [ "@security.context", "@router", "@session", "@translator", "@doctrine.orm.entity_manager" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    kernel.listener.exceptions_listener:
        class: %kernel.listener.exceptions_listener.class%
        arguments: [ "@session", "@router", "@translator" ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    procergs_logincidadao.client.form.type:
        class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\ClientFormType
        tags:
            - { name: form.type, alias: client_form_type }
        calls:
            - [setLcScope, ["%lc_supported_scopes%"]]

    procergs_logincidadao.client.base.form.type:
        class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\ClientBaseFormType
        tags:
            - { name: form.type, alias: client_base_form_type }

    procergs_logincidadao.category.form.type:
        class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\CategoryFormType
        tags:
            - { name: form.type, alias: category_form_type }
        calls:
            - [setSecurity, ["@security.context"]]
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]

    procergs_logincidadao.placeholder.form.type:
        class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\PlaceholderFormType
        tags:
            - { name: form.type, alias: placeholder_form_type }
        calls:
            - [setSecurity, ["@security.context"]]

    procergs_logincidadao.form.type.hidden_entity:
        class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\HiddenEntityType
        tags:
            - { name: form.type, alias: hidden_entity }

    procergs_logincidadao.form.type.switch:
        class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\SwitchType
        tags:
            - { name: form.type, alias: switch }
        calls:
            - [setTranslator, ["@translator"]]

    procergs_logincidadao.form.type.ajax_choice:
        class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\AjaxChoiceType
        tags:
            - { name: form.type, alias: ajax_choice }
        calls:
            - [setTranslator, ["@translator"]]
            - [setRouter, ["@router"]]

    procergs_logincidadao.person.resume.form.type:
        class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\PersonResumeFormType
        arguments: [ @lc.security.helper ]
        tags:
            - { name: form.type, alias: person_resume_form_type }
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
            - [setTranslator, ["@translator"]]
            - [setSecurity, ["@security.context"]]

    procergs.person.serialize.listenner:
        class: %procergs.person.serialize.listenner.class%
        scope: request
        arguments: [ @vich_uploader.templating.helper.uploader_helper, @templating.helper.assets, @kernel, @request ]
        tags:
            - { name: jms_serializer.event_listener, event: serializer.pre_serialize, method: onPreSerialize }

    procergs_logincidadao.person.address.form.type:
        class: %procergs_logincidadao.person.address.form.type.class%
        arguments: [ "@translator", "@doctrine.orm.entity_manager" ]
        tags:
            - { name: form.type, alias: lc_person_address }

    procergs_logincidadao.city.selector.form.type:
        class: %procergs_logincidadao.city.selector.form.type.class%
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: city_selector }

    procergs_logincidadao.state.selector.form.type:
        class: %procergs_logincidadao.state.selector.form.type.class%
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: state_selector }

    procergs_logincidadao.country.selector.form.type:
        class: %procergs_logincidadao.country.selector.form.type.class%
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: country_selector }

    procergs_logincidadao.idcard.form:
        class: %procergs_logincidadao.idcard.form.class%
        arguments: [ %lc_idcard_country_acronym%, @event_dispatcher ]
        tags:
            - { name: form.type, alias: lc_idcard_form }

    procergs_login_cidadao_notification.subscriber:
        class: %procergs_login_cidadao_notification.subscriber.class%
        arguments: [ @procergs.notification.handler, @procergs_logincidadao.mailer ]
        tags:
            - { name: kernel.event_subscriber }

    procergs.feature_hierarchy.voter:
        class: %security.access.role_hierarchy_voter.class%
        arguments: [ @security.role_hierarchy, 'FEATURE_' ]
        tags:
            - { name: security.voter }

    lc.security.helper:
        class: %procergs_logincidadao.security.helper.class%
        arguments: [ @security.context ]

    account.security_listener:
        class: %account.security_listener.class%
        arguments: [ @security.context, @session, @lc.action_logger ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

    lc.country_manager:
        class: PROCERGS\LoginCidadao\CoreBundle\Model\Manager\CountryManager
        arguments:
            - @doctrine.orm.entity_manager
            - PROCERGS\LoginCidadao\CoreBundle\Entity\Country

    lc.state_manager:
        class: PROCERGS\LoginCidadao\CoreBundle\Model\Manager\StateManager
        arguments:
            - @doctrine.orm.entity_manager
            - PROCERGS\LoginCidadao\CoreBundle\Entity\State

    lc.city_manager:
        class: PROCERGS\LoginCidadao\CoreBundle\Model\Manager\CityManager
        arguments:
            - @doctrine.orm.entity_manager
            - PROCERGS\LoginCidadao\CoreBundle\Entity\City

    lc.location.type:
        class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\CitySelectorComboType
        arguments:
            - @lc.country_manager
            - @lc.state_manager
            - @lc.city_manager
            - @procergs_logincidadao.profile_edit
            - @translator
        tags:
            - { name: form.type, alias: lc_location }
