# API
lc_api_core:
    resource: "@LoginCidadaoAPIBundle/Controller"
    defaults: { _format: json }
    prefix:   /

lc_Person:
    type: rest
    prefix: /
    resource: "@LoginCidadaoAPIBundle/Controller/PersonController.php"
    defaults: { _format: json }

lc_Badge:
    type: rest
    prefix: /
    resource: "@LoginCidadaoAPIBundle/Controller/BadgeController.php"
    defaults: { _format: json }

lc_PersonAddress:
    type: rest
    prefix: /
    resource: "@LoginCidadaoAPIBundle/Controller/PersonAddressController.php"
    name_prefix: api_1_
    defaults: { _format: json }

lc_Statistics:
    type: rest
    prefix: /
    resource: "@LoginCidadaoAPIBundle/Controller/StatisticsController.php"
    defaults: { _format: json }
